// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:habits/features/habits/data/models/habit_completion_model.dart';
import 'package:habits/features/habits/data/models/habit_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitCompletionModelAdapter());
    registerAdapter(HabitModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitCompletionModelAdapter());
    registerAdapter(HabitModelAdapter());
  }
}
